version: '3.9'
services:
  app:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - ./folderly-data:/folderly-data
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 80"]